theme: jekyll-theme-cayman
name: telegram.ext
title: Build a Chatbot using Telegram with R
description: An introduction to the Telegram Bot API and the telegram.ext package
repository: https://github.com/ebeneditos/telegram.ext
authors: Ernest Benedito
